label:  provider-beta
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///testdb?useSSL=true
    username: '{cipher}b90a92d36b84e040fc9a47fa240d7d581a17858566f54ba740958e0a463145bf'
    password: 123
  application:
    name:cloud-provider
  rabbitmq:
    port: 5672
    host: 192.168.146.220
    username: rabbit
    password: rabbit
