label:  provider-beta
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///testdb?useSSL=true
    username: '{cipher}AQAWiF9aeEzSuMA817LbtouK00fzeG0rIeBaBpudqBfPy6tcqAFY/7zE9lAJTrIl8cpLVe0Bf+2r2zeLe1dWTWOWw+yPNOrQYKeDFgLq8i6DT6ogTMTJOKDOyX3pZb7/zJHutm/r71nlYAfm6cKxLtSwtA30EL0xd0W4OcJX10uj2Wo09SGODe69VesjeXRX2ctVy85IHJF1ypaOW+7tnZSpM
ck9OaDDoMkIvwRwN5R0U6C+GFQcd0OzojdDGCk4eibdZP0/SUP+PCFyE+LTAm/imDSFmIP+ffrnot1U6/+5SeG0Q8I2b8ieUSNHZyPFP48X6Dzl6ARDainKjmOBiXvmvqgIQ1RQJ8qdTk5dTwzxOaD4aA/LZitxYlraHJvqpx8='
    password: 123
  application:
    name:cloud-provider
  rabbitmq:
    port: 5672
    host: 192.168.146.220
    username: rabbit
    password: rabbit
